output_md_root_dir: '/tmp/output_mds'
output_debug_dir: '/tmp/output_debugs'
text_formula_resized_shape: 768
page_resized_shape: 768

pix2text:
  layout:
    scores_thresh: 0.45
  text_formula:
    languages: [en, ch_sim]
    mfd:
      model_name: 'mfd'
    formula:
      model_name: mfr
      model_backend: onnx
    text:
      det_model_name: 'ch_PP-OCRv3_det'
      rec_model_name: 'doc-densenet_lite_136-gru'
      rec_model_backend: 'onnx'
