
pix2text:
  text_config:
    det_model_name: 'ch_PP-OCRv3_det'
    rec_model_backend: 'onnx'
    rec_model_name: 'doc-densenet_lite_666-gru_large'
  analyzer_config:
    model_name: 'mfd'
    model_type: 'yolov7'
    model_fp: '/Users/king/.cnstd/1.2/analysis/mfd-yolov7-epoch224-20230613.pt'
  formula_config:
    model_name: 'mfr-pro'
    model_backend: 'onnx'

