output_md_root_dir: '/tmp/output_mds'
output_debug_dir: '/tmp/output_debugs'
text_formula_resized_shape: 768
page_resized_shape: 768

pix2text:
  layout:
    scores_thresh: 0.45
  text_formula:
    languages: [en, ch_sim]
    mfd:
      model_name: mfd-pro
      model_path: ~/.pix2text/1.1/mfd-pro-onnx/mfd-pro-v20240618.onnx
    formula:
      model_name: mfr-pro
      model_backend: onnx
      model_dir: ~/.pix2text/1.1/mfr-pro-onnx
    text:
      det_model_name: 'ch_PP-OCRv3_det'
      rec_model_name: doc-densenet_lite_666-gru_large
      rec_model_backend: onnx
      rec_model_fp: ~/.cnocr/2.3/doc-densenet_lite_666-gru_large/cnocr-v2.3-doc-densenet_lite_666-gru_large-epoch=005-ft-model.onnx
