"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['latex_ocr.py']
DATA_FILES = []
OPTIONS = {'iconfile': './icons/logo.icns',
           'plist': {
               'CFBundleName': 'MyLatexOCR',  # Application Name
               'CFBundleDisplayName': 'MyLatexOCR',  # Application Display Name
               'CFBundleVersion': '0.01',  # Application version number
               'CFBundleIdentifier': 'MyLatexOCR',  # Application package name and unique identifier
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
